### ISSUE TITLE
Match backtracking is improperly handled

### ISSUE THREAD

**Issue by a-wortman** [a-wortman/poggle#14]
with the grammar
```
:components:
A := 0x04
B := 0x30
C := 0x24
D := (A|B):C
E := (A:B)|C

root := D:E
```
on the input
`0x30 0x24 0x04 0x30`

poggle inconsistently marks where to backtrack to, which results in an operation like `@bytes[nil]`.

error looks like
```
/toy/poggle/parser_parts/matcher.rb:11:in `[]': no implicit conversion from nil to integer (TypeError)
	from /toy/poggle/parser_parts/matcher.rb:11:in `next'
	from /toy/poggle/parser_parts/primitives/byte_body.rb:15:in `match'
	from /toy/poggle/parser_parts/body_proxy.rb:11:in `match'
```

**Comment by a-wortman** [comment]
Note that this would be expected to try `0x04`, `0x30`, `0x30:0x24`, and then `0x30:0x24:0x04:0x30`, successfully matching at the fourth step, after backtracking at the second. Instead the above error is raised.

**Comment by a-wortman** [comment]
forgot to close this. As mentioned in #15, this is resolved.
